#!/bin/bash
# Non-deterministic E2E test for the overengineering review agent.
#
# This test sends a fixture diff (containing deliberately overengineered code)
# to an LLM through the real agent prompt pipeline, then validates that:
#   1. The response is valid JSON matching the agent's output schema.
#   2. The findings reference at least one expected overengineering category.
#
# Uses pass@k with k=3 per the global test-suite standards.
# Results are logged in JSON Lines format for CI trend analysis.
#
# Usage:
#   bash scripts/test_e2e_overengineering.sh [--model <model-id>]
#
# Defaults to gpt-4o-mini for cost efficiency.

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SKILL_DIR="$(dirname "$SCRIPT_DIR")"
FIXTURE="$SKILL_DIR/test/fixtures/overengineered.diff"
AGENT_FILE="$SKILL_DIR/agents/overengineering.md"

K=3
MODEL="deepseek-v4-flash:cloud"
LOG_FILE="/tmp/codereview_e2e_overengineering_log.jsonl"

while [[ $# -gt 0 ]]; do
    case "$1" in
        --model)
            MODEL="$2"
            shift 2
            ;;
        --k)
            K="$2"
            shift 2
            ;;
        *)
            echo "Unknown argument: $1" >&2
            exit 1
            ;;
    esac
done

if [[ ! -f "$FIXTURE" ]]; then
    echo "FAIL: Fixture file not found: $FIXTURE" >&2
    exit 1
fi

if [[ ! -f "$AGENT_FILE" ]]; then
    echo "FAIL: Agent file not found: $AGENT_FILE" >&2
    exit 1
fi

AGENT_PROMPT=$(cat "$AGENT_FILE")
DIFF_CONTENT=$(cat "$FIXTURE")

# Build the full prompt: framing + agent prompt + diff
# This mirrors what generate.sh produces in the agents phase.
FULL_PROMPT="# Experimental Model Context

The code you are reviewing was generated by an experimental language model. This model is known to have specific failure patterns that your review should watch for:

- Overconfident code that papers over edge cases
- Plausible-looking but subtly incorrect logic
- Missing error handling for uncommon paths
- Hallucinated API usage or nonexistent library functions
- Security-relevant omissions (missing validation, auth checks)
- Verbose implementations that hide bugs in noise

Treat every line with heightened skepticism. Assume the model may have produced code that looks correct at first glance but contains hidden defects. Your review should be more thorough and less forgiving than a typical human-authored code review.

${AGENT_PROMPT}

## Code Under Review

The following diff is the code you must review:

\`\`\`diff
${DIFF_CONTENT}
\`\`\`

Return ONLY valid JSON matching the output schema. No markdown, no explanation."

# Expected overengineering patterns the fixture contains:
#   stdlib  — custom_json_parse reimplements json.loads
#   native  — fetch_with_retry manually creates asyncio streams instead of using aiohttp/httpx
#   yagni   — SorterFactory with one strategy, unused config params
#   delete  — unused_helper_function is dead code
#   shrink  — filter_active is verbose vs a list comprehension

PASS_COUNT=0
RESULTS=()

echo "=== E2E Overengineering Agent Test (pass@k=$K, model=$MODEL) ==="
echo ""

for i in $(seq 1 $K); do
    echo -n "Run $i/$K... "

    # Send prompt to LLM and capture output
    RAW_OUTPUT=$(echo "$FULL_PROMPT" | llm -m "$MODEL" 2>/dev/null || echo "")

    if [[ -z "$RAW_OUTPUT" ]]; then
        echo "FAIL (empty output)"
        RESULTS+=("fail")
        continue
    fi

    # Strip markdown code fences if present (Layer 2 fallback)
    CLEAN_OUTPUT=$(echo "$RAW_OUTPUT" | sed '/^```/d' | sed '/^~~~/d')

    # Validate JSON structure (Layer 1)
    STATUS=$(echo "$CLEAN_OUTPUT" | jq -r '.status // empty' 2>/dev/null || echo "")
    if [[ -z "$STATUS" ]]; then
        echo "FAIL (invalid JSON or missing status)"
        RESULTS+=("fail")
        continue
    fi

    # Validate status is one of the allowed values
    if [[ "$STATUS" != "passed" && "$STATUS" != "warning" && "$STATUS" != "failed" ]]; then
        echo "FAIL (invalid status: $STATUS)"
        RESULTS+=("fail")
        continue
    fi

    # Validate findings array exists
    FINDINGS_COUNT=$(echo "$CLEAN_OUTPUT" | jq '.findings | length' 2>/dev/null || echo "0")
    if [[ "$FINDINGS_COUNT" == "0" || -z "$FINDINGS_COUNT" ]]; then
        echo "FAIL (no findings — fixture should produce findings)"
        RESULTS+=("fail")
        continue
    fi

    # Validate each finding has required fields
    SCHEMA_VALID=$(echo "$CLEAN_OUTPUT" | jq -e '
        .findings[] |
        (.severity // empty | test("critical|high|medium|low")) and
        (.title // empty | length > 0) and
        (.description // empty | length > 0) and
        (.file // empty | length > 0) and
        (.suggested_fix // empty | length > 0)
        ' 2>/dev/null | wc -l | tr -d ' ')

    EXPECTED_FINDINGS=$(echo "$FINDINGS_COUNT" | tr -d ' ')
    if [[ "$SCHEMA_VALID" != "$EXPECTED_FINDINGS" ]]; then
        echo "FAIL (schema validation: $SCHEMA_VALID/$EXPECTED_FINDINGS findings valid)"
        RESULTS+=("fail")
        continue
    fi

    # Check that at least one finding references an expected pattern.
    # We look for keywords from the fixture's overengineering categories.
    DESCRIPTIONS=$(echo "$CLEAN_OUTPUT" | jq -r '.findings[].description' 2>/dev/null)
    TITLES=$(echo "$CLEAN_OUTPUT" | jq -r '.findings[].title' 2>/dev/null)
    ALL_TEXT="${DESCRIPTIONS} ${TITLES}"

    FOUND_CATEGORY=0
    for pattern in "json" "stdlib" "standard library" "sorted" "factory" "strategy" \
                   "dead code" "unused" "asyncio" "aiohttp" "httpx" \
                   "comprehension" "filter" "verbose" "shorter"; do
        if echo "$ALL_TEXT" | grep -qi "$pattern" 2>/dev/null; then
            FOUND_CATEGORY=$((FOUND_CATEGORY + 1))
        fi
    done

    if [[ "$FOUND_CATEGORY" -lt 2 ]]; then
        echo "FAIL (only matched $FOUND_CATEGORY/2 expected pattern keywords)"
        RESULTS+=("fail")
        continue
    fi

    echo "PASS ($FINDINGS_COUNT findings, $FOUND_CATEGORY pattern matches)"
    RESULTS+=("pass")
    PASS_COUNT=$((PASS_COUNT + 1))
done

# Compute pass@k and pass^k
PASS_AT_K=$(echo "scale=3; $PASS_COUNT / $K" | bc)
PASS_CONJ=$(echo "scale=3; $PASS_AT_K ^ $K" | bc 2>/dev/null || echo "n/a")

# Log result in JSON Lines format
TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
echo "{\"test\": \"overengineering-e2e\", \"k\": $K, \"pass\": $PASS_COUNT, \"pass@k\": $PASS_AT_K, \"pass^k\": $PASS_CONJ, \"timestamp\": \"$TIMESTAMP\", \"model\": \"$MODEL\"}" >> "$LOG_FILE"

echo ""
echo "=== E2E Test Summary ==="
echo "Model: $MODEL"
echo "Passed: $PASS_COUNT / $K"
echo "pass@k: $PASS_AT_K"
echo "pass^k: $PASS_CONJ"
echo "Log: $LOG_FILE"
echo ""

# A test passes the suite if pass@k >= 0.67 (at least 2 of 3 runs pass).
# This is the minimum bar for non-deterministic E2E per global guidance.
THRESHOLD=$(echo "scale=3; 2.0 / 3.0" | bc)
MEETS_THRESHOLD=$(echo "$PASS_AT_K >= $THRESHOLD" | bc)

if [[ "$MEETS_THRESHOLD" -eq 1 ]]; then
    echo "PASS: pass@k ($PASS_AT_K) >= threshold ($THRESHOLD)"
    exit 0
else
    echo "FAIL: pass@k ($PASS_AT_K) < threshold ($THRESHOLD)"
    exit 1
fi